### ISSUE TITLE
summaryList name is missleading

### ISSUE THREAD

**Issue by sousasag** [jdavidrcamacho/StarSearch#3]
https://github.com/jdavidrcamacho/StarSearch/blob/3ba9cdeaad56c6ff1b473d95b2ed3f7a60db4cdc/starsearch/phase3Archive.py#L580-L582

the name of the function is missleading.
I though the input was a list and not a filename
Actually having a function to have a list of names might be useful for scripting, and you can call that one from a simpler function let's call it summaryFile where you read the file create the list and call summaryList

**Comment by jdavidrcamacho** [comment]
Yes I agreed, I'll do the changes

**Comment by jdavidrcamacho** [comment]
Done, show we have the function `summaryList` that given a list of stars it will make a summary out of it. We also have a `summaryFile` that reads a file and makes the summary of the stars on the file (calling `summaryList` for it)
