### ISSUE TITLE
searchInstruments in Phase3 is in main archive?

### ISSUE THREAD

**Issue by sousasag** [jdavidrcamacho/StarSearch#5]
Can we search instruments in the phase3 archive?

https://github.com/jdavidrcamacho/StarSearch/blob/0abcd81d5d0006a59838a030340d4f00cb3fab37/starsearch/phase3Archive.py#L93-L118

**Comment by jdavidrcamacho** [comment]
Done

Now `searchInstruments(self, star, phase3 = True)` has a phase3 option. If True gives you the number of reduced spectra per instrument in the archive. If False gives you the number of raw spectra.
